### ISSUE TITLE
[parity-util-mem] consider using `zeroize` crate

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#181]
https://github.com/iqlusioninc/crates/tree/develop/zeroize seems to be the best option available atm.

~~Also, https://github.com/iqlusioninc/crates/tree/develop/secrecy could replace our `Secret` type.~~

**Comment by dvdplm** [comment]
I looked at `zeroize` previously and I think it's a great crate and you are probably right that we should use it. I particularly like the extensive docs and general willingness of the author to talk and educate about these issues. At the time I held back because I saw some code that was not clear to me ([this](https://github.com/iqlusioninc/crates/blob/develop/zeroize/src/lib.rs#L408)) and I didn't want to use code that I do not understand fully. That said, I can definitely be convinced!

The discussion about `Secret` is possibly slightly more involved as what we have in `parity-crypto` is sort of a mirror of what we have in `ethcore/crypto`. The plan is – at least in my head – to move code from there to `parity-crypto` and @cheme has essentially done that already but it's quite an invasive change so I think it's good to try to do it piece by piece and his approach [in that branch](https://github.com/paritytech/parity-ethereum/compare/master...cheme:crypto-only) is also something I need to review and think through carefully (mostly because I'm slow and ignorant, I don't think there's anything necessarily wrong with it).

**Comment by dvdplm** [comment]
(So maybe we should split out the `secrecy` conversation to its own ticket?)

**Comment by niklasad1** [comment]
/cc @twittner 

Any thoughts on `zeroize`? (I know you implemented something similar in parity-ethereum)

**Comment by twittner** [comment]
@niklasad1: I can only recommend it. We use it in rust-libp2p and I can think of no reason not to use it here too.
