### ISSUE TITLE
FreeBSD issue: 'estimate heapsize or feature allocator needed'

### ISSUE THREAD

**Issue by alexdupre** [paritytech/parity-common#543]
With the upgrade of openethereum from 3.2.4 to 3.2.5 something broke in FreeBSD dependencies/build. Apparently the change to `heapsize` dependency is now causing this issue at runtime:
```
Thread 'Worker Client1' panicked at 'internal error: entered unreachable code: estimate heapsize or feature allocator needed', /wrkdirs/usr/ports/net-p2p/openethereum/work/openethereum-3.2.5/cargo-crates/parity-util-mem-0.7.0/src/allocators.rs:110
```

**Comment by niklasad1** [comment]
Alright, it super hard to understand how which features `openethereum` has enabled on `parity-util-memory`.

Most likely, you must enable a specific `allocator` or use `estimate-heapsize` but should ideally be compile-time-error instead of a runtime error IMHO.

Can you please report which features you have enabled when building `parity-util-memory` and maybe try to enable a allocator such `--feature jemalloc-global`?

//cc @cheme @ordian you know this code far better than I do, maybe correct me if I'm wrong ^

**Comment by cheme** [comment]
I only see a change on https://github.com/paritytech/parity-common/pull/522, but should not change bsd behavior.
Same as Niklas, I would suggest trying to build with jemalloc (--feature parity-util-mem/jemalloc-global) and if unsupported, just remove the calls to allocators with --feature parity-util-mem/estimate-heapsize .

**Comment by ordian** [comment]
It seems that 3.2.4 was using a very old checkout of parity-ethereum with heapsize instead of parity-util-mem
https://github.com/openethereum/openethereum/blob/09967329af6fac1a9718f8b2b51d920a351a673e/crates/util/memory-cache/Cargo.toml
3.2.5 now uses an outdated parity-util-mem 0.7 with default features (no jemalloc)

They can apply a hotfix by using jemalloc (use `parity-util-mem = { version = "0.7", features = "jemalloc-global" }` in their `Cargo.toml`).
We could also add support for FreeBSD to parity-util-mem in the next version 0.9.1. The problem with that I'm don't know if it's possible to test it in CI easily and openethereum still uses an old version. The fix would be relative simple probably
https://github.com/paritytech/parity-common/blob/0867e488f6567e0d7fe13e78a14797ff019033f7/parity-util-mem/src/allocators.rs#L100

change to `unix`

**Comment by alexdupre** [comment]
Thanks for the suggestions, I confirm that the following patch fixed the issue: https://cgit.freebsd.org/ports/tree/net-p2p/openethereum/files/patch-cargo-crates_parity-util-mem-0.7.0_src_allocators.rs?id=fc7cedf081c73e164786d86c8adcd66c9a30e728

Probably even the use of jemalloc would have done (as it was in pre 3.2.5), but the above patch was simpler to be integrated in the ports tree. I think it makes sense to add it upstream.

**Comment by ordian** [comment]
@cheme do you remember what was the issue on macOS with the default allocator? macOS used to share a lot of code with FreeBSD, don't know how they differ in allocators now.

**Comment by cheme** [comment]
Not really, possibly I put condition this way because default allocator where not tested in other envt than linux. As a side note, I remember the ethereum client got better perf with jemalloc on linux so using it seem really worth it at the time (from when the client was still parity), but I never check on the other envt.

**Comment by ordian** [comment]
Probably because macOS doesn't have `malloc_usable_size`, but `malloc_size`
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/malloc_size.3.html
`malloc_usable_size` doesn't seem to be available on all `unix` systems, so the fix for FreeBSD would probably be another explicit listing.

Also [it is 5x slower on macOS than on Linux](https://lemire.me/blog/2017/09/15/how-fast-are-malloc_size-and-malloc_usable_size-in-c/), but that shouldn't be a major issue.

I also think using jemalloc (or mimalloc) is generally a good idea, but we don't control third-party software.
