### ISSUE TITLE
MSRV is unintentionally bumped in rlp 0.5.1 and kvdb-rocksdb 0.12.1 

### ISSUE THREAD

**Issue by xu-cheng** [paritytech/parity-common#577]
In 9e0e53a473aba2226a5c115f802762378fdf9fe7, `resolver = "2"` is added to `Cargo.toml`. This causes MSRV being bumped into 1.51 (ref: https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver). 

I am not sure whether this is intentional. However, it is generally not recommended to bump MSRV in a patch release.

**Comment by ordian** [comment]
I'm sorry if this caused any trouble. This change could have been avoided indeed.

However, keep in mind that we only officially support the latest stable and since bumping MSRV is considered a possibly-breaking change: https://doc.rust-lang.org/cargo/reference/semver.html#possibly-breaking-changing-the-minimum-version-of-rust-required, we reserve the right to do so in a minor or patch release e.g. for #475 in the future.

**Comment by xu-cheng** [comment]
Thanks for the explanation. It may be a good idea to document the MSRV change in the change log.
