### ISSUE TITLE
Switch to `rust-rocksdb` in `kvdb-rocksdb`

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-common#88]
`kvdb-rocksdb` currently uses our own fork of `rust-rocksdb`. The fork is diverged quite a bit. We should switch back to upstream, to get the latest updates. I started doing this in: https://github.com/paritytech/parity-common/commit/616b40150ded71f57f650067fcbc5c99d7c343e6

There are some `TODO`s on what is missing. We also need to upstream some functionality from our fork to upstream.

**Comment by dvdplm** [comment]
Do you think the `kvdb-rocksdb` test coverage is adequate or is this a good time to improve on that?

**Comment by bkchr** [comment]
I did not even know that there are tests 😅
There are not that much tests, but I think that a benchmark would be good to have. So that we can compare with and without switching to `rust-rocksdb`.
It would also nice to have at least compile tests for windows and Android, so that we know that we at least can compile for these platforms.

**Comment by tomtau** [comment]
btw, here's a bounty on this issue: https://www.bountysource.com/issues/67028819-switch-to-rust-rocksdb-in-kvdb-rocksdb

**Comment by ordian** [comment]
I've taken a look at this issue (in [ao-upstream-rocksdb](https://github.com/paritytech/parity-common/compare/ao-upstream-rocksdb) branch, only this commit 90b47c15948f538ea9ee10f01677f80d7707b923) and the following things are lacking in the upstream:
* `ColumnFamily` (`Column` in paritytech's fork) is not `Copy` and even lock-free (https://github.com/rust-rocksdb/rust-rocksdb/issues/279), this might incur significant perf overhead for transactions.
* Several `options.set_...` methods are missing (see todos in 90b47c15948f538ea9ee10f01677f80d7707b923, also cc https://github.com/rust-rocksdb/rust-rocksdb/issues/260).
* Several methods take `Options` by value (e.g. `DB::repair`), instead of by ref, which is not clonable.

**Comment by dvdplm** [comment]
> We also need to upstream some functionality from our fork to upstream.

@bkchr can you elaborate a bit on what it is that is missing upstream (other than the differences @ordian mentions)?

**Comment by bkchr** [comment]
I think the list of @ordian seems to be correct.

**Comment by expenses** [comment]
The only remaining change that we need is `Sync` `ColumnFamily`s:
```rust
error[E0277]: `*mut librocksdb_sys::rocksdb_column_family_handle_t` cannot be shared between threads safely
   --> kvdb-rocksdb/src/lib.rs:683:6
    |
683 | impl KeyValueDB for Database {
    |      ^^^^^^^^^^ `*mut librocksdb_sys::rocksdb_column_family_handle_t` cannot be shared between threads safely
    |
    = help: within `rocksdb::ColumnFamily`, the trait `std::marker::Sync` is not implemented for `*mut librocksdb_sys::rocksdb_column_family_handle_t`
    = note: required because it appears within the type `rocksdb::ColumnFamily`
```
